server:
  port: 6203

spring:
  application:
    name: lik-dr-product
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  main:
    allow-bean-definition-overriding: true

  # 数据库连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lik_tiger?serverTimezone=GMT%2B8

mybatis-plus:
  mapper-locations: classpath:com/lik/mapper/xml/*.xml
  configuration:
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    com.lik: debug

# feign 日志
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: lik-dr-product-producer
